import type { Category, Book, Review } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "ia",         name: "Inteligencia Artificial",   short: "IA",         color: "#13a06a", ink: "#fff",     count: 18 },
  { id: "cocina",     name: "Cocina y Gastronomía",      short: "Cocina",     color: "#1f2a44", ink: "#fff",     count: 14 },
  { id: "maternidad", name: "Maternidad y Embarazo",     short: "Maternidad", color: "#d8c5a8", ink: "#1a1208", count: 9  },
  { id: "personal",   name: "Desarrollo Personal",       short: "Personal",   color: "#1a1208", ink: "#fff",     count: 22 },
  { id: "negocios",   name: "Negocios y Emprendimiento", short: "Negocios",   color: "#2563d2", ink: "#fff",     count: 16 },
  { id: "salud",      name: "Salud y Bienestar",         short: "Salud",      color: "#c4a878", ink: "#1a1208", count: 11 },
];

export const BOOKS: Book[] = [
  {
    id: "ia-prompts-365",
    title: "365 Prompts que Cambiarán tu Trabajo",
    author: "Lucía Marín",
    cat: "ia",
    price: 29,
    oldPrice: 39,
    pages: 312,
    year: "2026",
    cover: { bg: "#13a06a", ink: "#fff", motif: "tri" },
    badge: "bestseller",
    rating: 4.9,
    reviews: 1284,
    short: "Un manual diario para integrar IA en tu rutina profesional sin perder el oficio.",
    long: "Un compendio de 365 prompts probados, organizados por escenario laboral. Para escritores, marketers, diseñadores, abogados y product managers que quieren acelerar su trabajo con criterio. Cada prompt incluye contexto, variantes y ejemplos de salida.",
    includes: ["365 prompts editables", "12 plantillas de flujo", "Checklist de seguridad de datos", "Acceso a actualizaciones durante 1 año"],
  },
  {
    id: "cocina-pan-madre",
    title: "El Arte del Pan de Masa Madre",
    author: "Andreu Puig",
    cat: "cocina",
    price: 24,
    pages: 184,
    year: "2025",
    cover: { bg: "#1f2a44", ink: "#f3e9d2", motif: "spine" },
    badge: "bestseller",
    rating: 4.8,
    reviews: 612,
    short: "Del fermento al horno doméstico — la fórmula sencilla detrás de la corteza perfecta.",
    long: "Veinte panes esenciales explicados con la pausa de un panadero artesano. Hidrataciones, plegados, retardos, hornos caseros y trucos para fallar menos. Fotografía paso a paso y tabla de errores comunes.",
    includes: ["20 recetas paso a paso", "Calendario de fermentación", "Tabla de errores y soluciones", "Plantilla de cuaderno de panadero"],
  },
  {
    id: "maternidad-primer-ano",
    title: "El Primer Año, sin manuales",
    author: "Inés Carballo",
    cat: "maternidad",
    price: 22,
    pages: 232,
    year: "2026",
    cover: { bg: "#d8c5a8", ink: "#1a1208", motif: "tri" },
    badge: "nuevo",
    rating: 4.9,
    reviews: 318,
    short: "Una guía honesta —no ideológica— para acompañar a tu bebé los primeros doce meses.",
    long: "Una lectura serena sobre sueño, lactancia, llantos y vínculo. Sin recetas mágicas. Con base en pediatría actual y la experiencia de madres reales. Pensado para leerse en pequeños tramos, cuando hay tiempo.",
    includes: ["52 mini-capítulos por semana", "Cuadernos de observación imprimibles", "Guía rápida de dudas frecuentes"],
  },
  {
    id: "personal-tres-horas",
    title: "Tres Horas Profundas",
    author: "Marc Fonseca",
    cat: "personal",
    price: 19,
    pages: 156,
    year: "2026",
    cover: { bg: "#1a1208", ink: "#f3e9d2", motif: "rule" },
    badge: "bestseller",
    rating: 4.7,
    reviews: 904,
    short: "Cómo recuperar tres horas de trabajo profundo al día —sin gurús ni apps milagrosas.",
    long: "Un protocolo breve, basado en investigación de atención y rutinas de creadores. Sin pirotecnia. Lo que queda cuando quitas todo lo que no funciona.",
    includes: ["Protocolo de 21 días", "Plantilla de bitácora", "Audio-resumen de 28 minutos"],
  },
  {
    id: "negocios-marca-pequena",
    title: "Marca Pequeña, Beneficio Grande",
    author: "Alba Rentería",
    cat: "negocios",
    price: 27,
    pages: 264,
    year: "2025",
    cover: { bg: "#2563d2", ink: "#fff", motif: "tri" },
    rating: 4.8,
    reviews: 421,
    short: "El playbook para marcas de menos de cinco personas con ambición desproporcionada.",
    long: "Posicionamiento, precio, narrativa y operativa para fundadores en solitario o equipos diminutos. Casos reales —no teóricos— de marcas que facturan siete cifras con menos de cinco personas.",
    includes: ["Plantillas de posicionamiento", "Calculadora de pricing", "8 estudios de caso reales"],
  },
  {
    id: "salud-respirar",
    title: "Volver a Respirar",
    author: "Nora Aguilar",
    cat: "salud",
    price: 18,
    pages: 148,
    year: "2026",
    cover: { bg: "#c4a878", ink: "#1a1208", motif: "spine" },
    badge: "nuevo",
    rating: 4.6,
    reviews: 207,
    short: "Doce ejercicios respiratorios para regular el sistema nervioso en menos de cinco minutos.",
    long: "Un manual de bolsillo basado en fisiología respiratoria y trabajo somático. Ejercicios cortos, ilustrados y secuenciados por intención: dormir, concentrarte, calmarte, recuperar.",
    includes: ["12 ejercicios ilustrados", "Audio-guías de 3 a 5 min", "Tarjetas imprimibles"],
  },
  {
    id: "ia-escritura-creativa",
    title: "Escribir con la Máquina",
    author: "Tomás Vidal",
    cat: "ia",
    price: 25,
    pages: 196,
    year: "2026",
    cover: { bg: "#0f3a2e", ink: "#e8d9b5", motif: "rule" },
    badge: "nuevo",
    rating: 4.7,
    reviews: 158,
    short: "Cómo usar IA para escribir mejor, no más rápido —técnica y ética para autores.",
    long: "Un libro para escritores que no quieren externalizar su voz. Plantillas de coautoría, técnicas de revisión, edición conceptual con IA y conversaciones honestas sobre el oficio.",
    includes: ["18 protocolos de coautoría", "Plantilla de estilo personal", "Conversación con 4 escritores"],
  },
  {
    id: "cocina-fermentos",
    title: "Cocina Viva",
    author: "Greta Bauer",
    cat: "cocina",
    price: 21,
    pages: 172,
    year: "2025",
    cover: { bg: "#7a3a1f", ink: "#f3e9d2", motif: "tri" },
    rating: 4.8,
    reviews: 244,
    short: "Fermentos caseros sin miedo: chucrut, kimchi, kombucha y vinagres de la huerta.",
    long: "Un libro práctico con base científica clara. Tiempos, temperaturas, signos de fermentación correcta y errores que se pueden recuperar. Para quien quiere empezar mañana mismo.",
    includes: ["24 recetas de base", "Calendario por estación", "Tabla de seguridad alimentaria"],
  },
];

export const REVIEWS: Review[] = [
  { name: "Carla M.", rating: 5, date: "hace 2 semanas", text: "Lo compré por curiosidad y lo terminé en dos sentadas. Está escrito como si te hablara una amiga inteligente. Volveré a por más." },
  { name: "Joaquín R.", rating: 5, date: "hace 1 mes", text: "Sin paja. Cero relleno motivacional. Material directamente aplicable desde el primer capítulo." },
  { name: "Lía S.", rating: 4, date: "hace 1 mes", text: "Muy bueno. Le pondría cinco estrellas si la maquetación tuviera más espacio para mis notas." },
];
