import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ebooks = [
  {
    slug: "ia-prompts-365",
    title: "365 Prompts que Cambiarán tu Trabajo",
    description: "Un manual diario para integrar IA en tu rutina profesional sin perder el oficio.",
    longDesc: "Un compendio de 365 prompts probados, organizados por escenario laboral. Para escritores, marketers, diseñadores, abogados y product managers que quieren acelerar su trabajo con criterio.",
    price: 29,
    oldPrice: 39,
    category: "ia",
    pages: 312,
    year: "2026",
    badge: "bestseller",
    rating: 4.9,
    reviews: 1284,
    coverBg: "#13a06a",
    coverInk: "#ffffff",
    coverMotif: "tri",
    includes: ["365 prompts editables", "12 plantillas de flujo", "Checklist de seguridad de datos", "Acceso a actualizaciones durante 1 año"],
  },
  {
    slug: "cocina-pan-madre",
    title: "El Arte del Pan de Masa Madre",
    description: "Del fermento al horno doméstico — la fórmula sencilla detrás de la corteza perfecta.",
    longDesc: "Veinte panes esenciales explicados con la pausa de un panadero artesano. Hidrataciones, plegados, retardos, hornos caseros y trucos para fallar menos.",
    price: 24,
    category: "cocina",
    pages: 184,
    year: "2025",
    badge: "bestseller",
    rating: 4.8,
    reviews: 612,
    coverBg: "#1f2a44",
    coverInk: "#f3e9d2",
    coverMotif: "spine",
    includes: ["20 recetas paso a paso", "Calendario de fermentación", "Tabla de errores y soluciones", "Plantilla de cuaderno de panadero"],
  },
  {
    slug: "maternidad-primer-ano",
    title: "El Primer Año, sin manuales",
    description: "Una guía honesta —no ideológica— para acompañar a tu bebé los primeros doce meses.",
    longDesc: "Una lectura serena sobre sueño, lactancia, llantos y vínculo. Sin recetas mágicas. Con base en pediatría actual y la experiencia de madres reales.",
    price: 22,
    category: "maternidad",
    pages: 232,
    year: "2026",
    badge: "nuevo",
    rating: 4.9,
    reviews: 318,
    coverBg: "#d8c5a8",
    coverInk: "#1a1208",
    coverMotif: "tri",
    includes: ["52 mini-capítulos por semana", "Cuadernos de observación imprimibles", "Guía rápida de dudas frecuentes"],
  },
  {
    slug: "personal-tres-horas",
    title: "Tres Horas Profundas",
    description: "Cómo recuperar tres horas de trabajo profundo al día —sin gurús ni apps milagrosas.",
    longDesc: "Un protocolo breve, basado en investigación de atención y rutinas de creadores. Sin pirotecnia. Lo que queda cuando quitas todo lo que no funciona.",
    price: 19,
    category: "personal",
    pages: 156,
    year: "2026",
    badge: "bestseller",
    rating: 4.7,
    reviews: 904,
    coverBg: "#1a1208",
    coverInk: "#f3e9d2",
    coverMotif: "rule",
    includes: ["Protocolo de 21 días", "Plantilla de bitácora", "Audio-resumen de 28 minutos"],
  },
  {
    slug: "negocios-marca-pequena",
    title: "Marca Pequeña, Beneficio Grande",
    description: "El playbook para marcas de menos de cinco personas con ambición desproporcionada.",
    longDesc: "Posicionamiento, precio, narrativa y operativa para fundadores en solitario o equipos diminutos. Casos reales —no teóricos— de marcas que facturan siete cifras.",
    price: 27,
    category: "negocios",
    pages: 264,
    year: "2025",
    rating: 4.8,
    reviews: 421,
    coverBg: "#2563d2",
    coverInk: "#ffffff",
    coverMotif: "tri",
    includes: ["Plantillas de posicionamiento", "Calculadora de pricing", "8 estudios de caso reales"],
  },
  {
    slug: "salud-respirar",
    title: "Volver a Respirar",
    description: "Doce ejercicios respiratorios para regular el sistema nervioso en menos de cinco minutos.",
    longDesc: "Un manual de bolsillo basado en fisiología respiratoria y trabajo somático. Ejercicios cortos, ilustrados y secuenciados por intención.",
    price: 18,
    category: "salud",
    pages: 148,
    year: "2026",
    badge: "nuevo",
    rating: 4.6,
    reviews: 207,
    coverBg: "#c4a878",
    coverInk: "#1a1208",
    coverMotif: "spine",
    includes: ["12 ejercicios ilustrados", "Audio-guías de 3 a 5 min", "Tarjetas imprimibles"],
  },
  {
    slug: "ia-escritura-creativa",
    title: "Escribir con la Máquina",
    description: "Cómo usar IA para escribir mejor, no más rápido —técnica y ética para autores.",
    longDesc: "Un libro para escritores que no quieren externalizar su voz. Plantillas de coautoría, técnicas de revisión, edición conceptual con IA.",
    price: 25,
    category: "ia",
    pages: 196,
    year: "2026",
    badge: "nuevo",
    rating: 4.7,
    reviews: 158,
    coverBg: "#0f3a2e",
    coverInk: "#e8d9b5",
    coverMotif: "rule",
    includes: ["18 protocolos de coautoría", "Plantilla de estilo personal", "Conversación con 4 escritores"],
  },
  {
    slug: "cocina-fermentos",
    title: "Cocina Viva",
    description: "Fermentos caseros sin miedo: chucrut, kimchi, kombucha y vinagres de la huerta.",
    longDesc: "Un libro práctico con base científica clara. Tiempos, temperaturas, signos de fermentación correcta y errores que se pueden recuperar.",
    price: 21,
    category: "cocina",
    pages: 172,
    year: "2025",
    rating: 4.8,
    reviews: 244,
    coverBg: "#7a3a1f",
    coverInk: "#f3e9d2",
    coverMotif: "tri",
    includes: ["24 recetas de base", "Calendario por estación", "Tabla de seguridad alimentaria"],
  },
];

async function main() {
  console.log("Seeding ebooks...");
  for (const book of ebooks) {
    await prisma.ebook.upsert({
      where: { slug: book.slug },
      update: {},
      create: book,
    });
    console.log(`  ✓ ${book.title}`);
  }
  console.log("Seed complete.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
